name: Build and Release (Docker Mode)

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  packages: write
  actions: read

jobs:
  prepare-env:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Builder Image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true
        tags: arch-gtk4-builder:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build-project:
    needs: prepare-env
    runs-on: ubuntu-latest
    container:
      image: arch-gtk4-builder:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Check Formatting
      run: cargo fmt --check
    
    - name: Run Clippy
      run: cargo clippy -- -D warnings

    - name: Build Project
      run: cargo build --release

    - name: Prepare Artifacts
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "IS_RELEASE=true" >> $GITHUB_ENV
        else
          echo "VERSION=latest" >> $GITHUB_ENV
          echo "IS_RELEASE=false" >> $GITHUB_ENV
        fi
        
        cd target/release/
        tar -czf ../../dummy-power-menu.tar.gz dummy-power-menu
        cd ../../

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false
        generate_release_notes: true
        files: |
          dummy-power-menu.tar.gz
